package sportmanagementhibernatetestrun;
// Generated Jul 21, 2020 12:13:49 PM by Hibernate Tools 4.3.1



/**
 * SportsManagement generated by hbm2java
 */
public class SportsManagement  implements java.io.Serializable {


     private String employees;

    public SportsManagement() {
    }

    public SportsManagement(String employees) {
       this.employees = employees;
    }
   
    public String getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(String employees) {
        this.employees = employees;
    }




}


