package sportmanagementhibernatetestrun;
// Generated Jul 21, 2020 12:13:49 PM by Hibernate Tools 4.3.1



/**
 * SportsClub generated by hbm2java
 */
public class SportsClub  implements java.io.Serializable {


     private String typeOfSports;
     private Integer age;
     private Integer numberOfWins;

    public SportsClub() {
    }

	
    public SportsClub(String typeOfSports) {
        this.typeOfSports = typeOfSports;
    }
    public SportsClub(String typeOfSports, Integer age, Integer numberOfWins) {
       this.typeOfSports = typeOfSports;
       this.age = age;
       this.numberOfWins = numberOfWins;
    }
   
    public String getTypeOfSports() {
        return this.typeOfSports;
    }
    
    public void setTypeOfSports(String typeOfSports) {
        this.typeOfSports = typeOfSports;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Integer getNumberOfWins() {
        return this.numberOfWins;
    }
    
    public void setNumberOfWins(Integer numberOfWins) {
        this.numberOfWins = numberOfWins;
    }




}


